# Generated by Django 5.2 on 2025-04-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0002_server_user_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
