# Generated by Django 5.2 on 2025-04-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0003_server_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ssh_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
