# Generated by Django 5.2 on 2025-04-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0004_server_ssh_password_server_ssh_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
