# Generated by Django 5.2 on 2025-04-14 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0005_remove_service_protocol_remove_service_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='webui.server'),
        ),
    ]
