# Generated by Django 5.2 on 2025-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0010_server_auto_wake_wolschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='wolschedule',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wolschedule',
            name='type',
            field=models.CharField(choices=[('WAKE', 'WAKE'), ('SHUTDOWN', 'SHUTDOWN')], default='WAKE', max_length=10),
            preserve_default=False,
        ),
    ]
