# Generated by Django 5.2.2 on 2025-06-06 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0011_wolschedule_enabled_wolschedule_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('show_networks', models.BooleanField(default=True)),
                ('show_servers', models.BooleanField(default=True)),
                ('show_services', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_password',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_username',
        ),
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='status_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='port',
            field=models.IntegerField(default=80),
        ),
        migrations.CreateModel(
            name='Homelab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wiki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homelab', to='webui.wiki')),
            ],
        ),
        migrations.AddField(
            model_name='network',
            name='homelab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='webui.homelab'),
        ),
        migrations.AddField(
            model_name='server',
            name='homelab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='webui.homelab'),
        ),
        migrations.CreateModel(
            name='ShutdownURLConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=300)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shutdown_url', to='webui.server')),
            ],
        ),
    ]
