# Generated by Django 5.2.2 on 2025-06-08 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0013_alter_homelab_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homelab',
            name='wiki',
        ),
        migrations.AddField(
            model_name='wiki',
            name='homelab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wiki', to='webui.homelab'),
            preserve_default=False,
        ),
    ]
