# Generated by Django 5.2.2 on 2025-06-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0014_remove_homelab_wiki_wiki_homelab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wiki',
            old_name='show_networks',
            new_name='show_network_graph',
        ),
        migrations.AddField(
            model_name='service',
            name='endpoint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
