# Generated by Django 5.2.2 on 2025-06-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0016_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='title',
            field=models.CharField(default='NO TITLE SET', max_length=100),
            preserve_default=False,
        ),
    ]
