# Generated by Django 5.2.2 on 2025-06-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0017_wiki_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_networks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_wiki',
            field=models.BooleanField(default=True),
        ),
    ]
