# Generated by Django 5.2.2 on 2025-06-15 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0018_userprofile_show_networks_userprofile_show_wiki'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerUptimeStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.JSONField(default=dict)),
                ('initialized', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_statistic', to='webui.server', unique=True)),
            ],
        ),
    ]
