# Generated by Django 5.2.2 on 2025-06-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0019_serveruptimestatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveruptimestatistic',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='serveruptimestatistic',
            name='matrix',
            field=models.JSONField(default={'not': 'initialized'}),
        ),
    ]
