# Generated by Django 5.2.2 on 2025-06-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0021_userprofile_dark_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Enable or disable Dark Mode'),
        ),
    ]
