# Generated by Django 5.2.2 on 2025-06-26 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0022_alter_userprofile_dark_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='status_url',
        ),
        migrations.AddField(
            model_name='wolschedule',
            name='enable_log',
            field=models.BooleanField(default=True, help_text='Enable or disable logging for the WOL schedule'),
        ),
        migrations.AddField(
            model_name='wolschedule',
            name='logs',
            field=models.JSONField(blank=True, help_text='Logs of the WOL schedule execution', null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='auto_wake',
            field=models.BooleanField(default=False, help_text='Automatically wake the server on access'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the server', null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.IntegerField(blank=True, default=80, help_text='Will be used to check if the server is online', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Enable or disable Dark Mode (experimental)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_selected_homelab',
            field=models.ForeignKey(blank=True, help_text='The last selected homelab for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webui.homelab'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='show_networks',
            field=models.BooleanField(default=True, help_text='Show or hide networks in the UI'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='show_wiki',
            field=models.BooleanField(default=True, help_text='Show or hide the wiki in the UI'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='The user this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='public',
            field=models.BooleanField(default=False, help_text='Make the wiki accessible public'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='show_network_graph',
            field=models.BooleanField(default=True, help_text='Show a network graph in the wiki'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='show_servers',
            field=models.BooleanField(default=True, help_text='Show servers in the wiki'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='show_services',
            field=models.BooleanField(default=True, help_text='Show services in the wiki'),
        ),
        migrations.AlterField(
            model_name='wolschedule',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable the WOL schedule'),
        ),
        migrations.AlterField(
            model_name='wolschedule',
            name='repeat',
            field=models.BooleanField(default=False, help_text='Repeat the WOL schedule'),
        ),
    ]
