# Generated by Django 5.2.2 on 2025-06-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0023_remove_server_status_url_wolschedule_enable_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wolschedule',
            name='enable_log',
            field=models.TextField(default='', help_text='Enable or disable logging for the WOL schedule'),
        ),
    ]
