# Generated by Django 5.2.2 on 2025-06-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0024_alter_wolschedule_enable_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='pinned_services',
            field=models.ManyToManyField(blank=True, help_text='Services pinned to the wiki for quick access', related_name='pinned_wikis', to='webui.service'),
        ),
        migrations.AlterField(
            model_name='wolschedule',
            name='logs',
            field=models.JSONField(blank=True, default='', help_text='Logs of the WOL schedule execution', null=True),
        ),
    ]
