# Generated by Django 5.2.2 on 2025-07-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0025_wiki_pinned_services_alter_wolschedule_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.URLField(blank=True, help_text='URL to access the service, if applicable. Used to redirect to the service.', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='endpoint',
            field=models.CharField(blank=True, help_text='Domain or IP address of the service. Used for online checking.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Enable Dark Mode (experimental)'),
        ),
    ]
