# Generated by Django 5.2.4 on 2025-07-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0026_service_url_alter_service_endpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_execution', models.DateTimeField(auto_now=True, help_text='Timestamp of the last cron execution')),
                ('execution_count', models.IntegerField(default=0, help_text='Total number of cron executions')),
                ('is_healthy', models.BooleanField(default=True, help_text='Whether cron is considered healthy')),
                ('last_error', models.TextField(blank=True, help_text='Last error message if any', null=True)),
            ],
            options={
                'verbose_name': 'Cron Status',
                'verbose_name_plural': 'Cron Statuses',
            },
        ),
    ]
