# Generated by Django 5.2.2 on 2025-07-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0026_service_url_alter_service_endpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_cron', models.DateTimeField(blank=True, null=True)),
                ('exception', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'App State',
                'verbose_name_plural': 'App State',
            },
        ),
    ]
