# Generated by Django 5.2.2 on 2025-07-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0027_appstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wolschedule',
            name='enable_log',
            field=models.BooleanField(default=True, help_text='Enable or disable logging for the WOL schedule'),
        ),
        migrations.AlterField(
            model_name='wolschedule',
            name='logs',
            field=models.TextField(blank=True, default='', help_text='Logs of the WOL schedule execution', null=True),
        ),
    ]
