# Generated by Django 5.2.2 on 2025-07-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0028_alter_wolschedule_enable_log_alter_wolschedule_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstate',
            name='exception',
            field=models.TextField(default=''),
        ),
    ]
