# Generated by Django 5.2.2 on 2025-07-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0029_alter_appstate_exception'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstate',
            name='last_exceptipon',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
