# Generated by Django 5.2.2 on 2025-07-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0031_homelab_subnet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homelab',
            name='subnet',
        ),
        migrations.AddField(
            model_name='network',
            name='subnet',
            field=models.CharField(blank=True, help_text='Subnet of the homelab, e.g. 192.168.1.0/24', max_length=20, null=True),
        ),
    ]
