# Generated by Django 5.2.2 on 2025-07-12 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0032_remove_homelab_subnet_network_subnet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='subnet',
            field=models.CharField(blank=True, help_text='Subnet of the network, e.g. 192.168.1.0/24', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='IngressRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this rule', max_length=100)),
                ('hostname', models.CharField(help_text='Hostname to match (e.g., service.lan)', max_length=100, unique=True)),
                ('path_prefix', models.CharField(default='/', help_text='Path prefix to match (e.g., /api/)', max_length=200)),
                ('forward_type', models.CharField(choices=[('PROXY', 'Proxy Pass'), ('REDIRECT', '301 Redirect')], default='PROXY', max_length=10)),
                ('preserve_host', models.BooleanField(default=True, help_text='Preserve original Host header')),
                ('strip_path_prefix', models.BooleanField(default=False, help_text='Remove path prefix before forwarding')),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100, help_text='Lower numbers have higher priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homelab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingress_rules', to='webui.homelab')),
                ('target_service', models.ForeignKey(help_text='Service to forward requests to', on_delete=django.db.models.deletion.CASCADE, related_name='ingress_rules', to='webui.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'hostname', 'path_prefix'],
            },
        ),
        migrations.CreateModel(
            name='IngressUsageAggregated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('request_count', models.IntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('unique_ips', models.IntegerField(default=0)),
                ('ingress_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='webui.ingressrule')),
            ],
            options={
                'indexes': [models.Index(fields=['ingress_rule', '-date'], name='webui_ingre_ingress_beb593_idx')],
                'unique_together': {('ingress_rule', 'date')},
            },
        ),
        migrations.CreateModel(
            name='IngressUsageStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('bytes_sent', models.BigIntegerField(blank=True, null=True)),
                ('ingress_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='webui.ingressrule')),
            ],
            options={
                'indexes': [models.Index(fields=['ingress_rule', '-timestamp'], name='webui_ingre_ingress_1bc0f9_idx'), models.Index(fields=['timestamp'], name='webui_ingre_timesta_14219e_idx')],
            },
        ),
    ]
