# Generated by Django 5.2.2 on 2025-07-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0033_alter_network_subnet_ingressrule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingressusagestatistic',
            name='ingress_rule',
        ),
        migrations.DeleteModel(
            name='IngressUsageAggregated',
        ),
        migrations.DeleteModel(
            name='IngressUsageStatistic',
        ),
    ]
