# Generated by Django 5.2.2 on 2025-07-12 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0034_remove_ingressusagestatistic_ingress_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngressRule',
            new_name='Ingress',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_ingress',
            field=models.BooleanField(default=True, help_text='Show or hide ingress rules in the UI'),
        ),
    ]
