# Generated by Django 5.2.2 on 2025-07-12 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0035_rename_ingressrule_ingress_userprofile_show_ingress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingress',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable this ingress rule'),
        ),
        migrations.AlterField(
            model_name='ingress',
            name='homelab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingresses', to='webui.homelab'),
        ),
        migrations.AlterField(
            model_name='ingress',
            name='target_service',
            field=models.ForeignKey(help_text='Service to forward requests to', on_delete=django.db.models.deletion.CASCADE, related_name='ingresses', to='webui.service'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='show_ingress',
            field=models.BooleanField(default=True, help_text='Show or hide ingress section in the UI'),
        ),
    ]
