# Generated by Django 5.2.2 on 2025-07-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0036_alter_ingress_enabled_alter_ingress_homelab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingress',
            name='hostname',
            field=models.CharField(help_text='Hostname to match (e.g., service.lan)', max_length=100),
        ),
    ]
