# Generated by Django 5.2.2 on 2025-07-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0037_alter_ingress_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='pinned_servers',
            field=models.ManyToManyField(blank=True, help_text='Servers pinned to the wiki for quick access', to='webui.server'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='pinned_services',
            field=models.ManyToManyField(blank=True, help_text='Services pinned to the wiki for quick access', to='webui.service'),
        ),
    ]
