# Generated by Django 5.2.2 on 2025-07-21 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webui', '0038_wiki_pinned_servers_alter_wiki_pinned_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='webui.network'),
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the maintenance plan', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the maintenance plan', null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('scheduled_date', models.DateTimeField(help_text='When the maintenance is scheduled')),
                ('repeat_interval', models.IntegerField(default=0, help_text='Repeat interval in days (0 for no repeat)')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='webui.userprofile')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK'), ('REMARK', 'Remark'), ('ERROR', 'Error'), ('BLOCKED', 'Blocked'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled'), ('UNKNOWN', 'Unknown')], default='OK', help_text='Result of the maintenance task', max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date of the maintenance task')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the maintenance task', null=True)),
                ('certifier', models.ForeignKey(help_text='User who certified the maintenance task', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reports', to='webui.userprofile')),
                ('maintenance_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='webui.maintenanceplan')),
            ],
        ),
    ]
