# Generated by Django 5.2.2 on 2025-07-21 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0039_alter_server_network_maintenanceplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplan',
            name='homelab',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='webui.homelab'),
            preserve_default=False,
        ),
    ]
